export const REGREQUEST = "REGREQUEST"
export const REGSUCCESS = "REGSUCCESS"
export const REGFAILURE = "REGFAILURE"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const IS_AUTH = "IS_AUTH"
export const LOGIN_USER = "LOGIN_USER"